### ISSUE TITLE
Strange WebStorm alert after import stickyfill

### ISSUE THREAD

**Issue by koddr** [wilddeer/stickyfill#100]
Hello.

I have very strange WebStorm alert after import `stickyfill` in my React.js app:

<img width="1281" alt="screen shot 2018-06-26 at 11 23 36" src="https://user-images.githubusercontent.com/11155743/41898906-cab99356-7933-11e8-96f0-be89be38cbd4.png">

What's wrong? Btw, `stickyfill` is working great, but this alert make me worry..
Thanks!

**Comment by wilddeer** [comment]
No idea ¯\\\_(ツ)_/¯

**Comment by fpetitit** [comment]
Hello, I solved this by setting the import like that : 
```
import * as Stickyfill from 'stickyfilljs';
```

**Comment by koddr** [comment]
@fpetitit awesome, thanks :)

Would be great to update docs with this, @wilddeer ;)

**Comment by wilddeer** [comment]
I personally think that this is a bug that should be reported to the WebStorm team. There’s no reason to update the docs just because WebStorm shows a warning. The import in your code works just fine.

**Comment by sunnyrjuneja** [comment]
not very important but have the same issue with VS Code. could be an issue with the way the project is setup or the compiler is being read.
