### ISSUE TITLE
Make available via npm for browserify

### ISSUE THREAD

**Issue by wolfgangschoeffel** [wilddeer/stickyfill#11]
Very nice polyfill! Would be cool to make it available as npm module for browserify.

**Comment by cascornelissen** [comment]
I case anyone is still looking for this, I found an NPM package that wraps this polyfill: [stickyfill on NPM](https://www.npmjs.com/package/stickyfill).

**Comment by TrySound** [comment]
@wilddeer Any updates?

**Comment by TrySound** [comment]
@wilddeer Let's move this to npm? I have exp and can help with this.

**Comment by dmitry** [comment]
What about: https://github.com/rollup/rollup ?

**Comment by vincentorback** [comment]
Any movement on this? Would be awesome!

**Comment by sapegin** [comment]
I’d like to have this on npm too. Bower is dead anyway.

**Comment by geschwendt** [comment]
While we wait for this, its possible to run `npm i wilddeer/stickyfill#1.1.3` as a workaround.

**Comment by sapegin** [comment]
@wilddeer Any update on this?

**Comment by danimalweb** [comment]
This would be great.

**Comment by FDiskas** [comment]
+1

**Comment by FDiskas** [comment]
To work with browserify you need:
```
npm install browserify-shim --save-dev
```
```
npm i wilddeer/stickyfill#1.1.4
```

package.json:
```
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "browserify-shim": {
    "Stickyfill": {
      "depends": [
        "jquery"
      ],
      "exports": "$:Stickyfill"
    }
  }
```

Then just
`require('Stickyfill');`

**Comment by erquhart** [comment]
@wilddeer pretty please?

This isn't something someone can PR, you would have to publish it to npm yourself. There's another package that wraps this as a web module, but I'd prefer to go straight to the source if possible.

**Comment by godban** [comment]
+1

**Comment by godban** [comment]
> I'm really busy right now, but contributions are always appreciated.

The thing is that only persons from owners list can publish package to npm.
Not sure if it will work for initial publish, but you can try to delegate this to trusted person.

More about manage package owners here:  [https://docs.npmjs.com/cli/owner](https://docs.npmjs.com/cli/owner)

You have great solution, sad that it's not easy reachable.

**Comment by christophemarois** [comment]
I have successfully installed it as a module with `yarn save stickyfill`, and this is how I use it inside of webpack:

```javascript
// Bind instance to window.Stickyfill if it doesn't exist yet
import installStickyfill from 'stickyfill'
if (!window.Stickyfill) window.Stickyfill = installStickyfill()
```

**Comment by wilddeer** [comment]
Took me 3 years ¯\\\_(ツ)_/¯

`npm install stickyfilljs --save` or `yarn add stickyfilljs`. Beware, new API has nothing in common with the old versions.
