### ISSUE TITLE
If window.pageYOffset < 0 it should not unstick.

### ISSUE THREAD

**Issue by wolfgangschoeffel** [wilddeer/stickyfill#12]
In Chrome and Safari the window.pageYOffset can become negative. I think in that case a sticky element should not unstick.

**Comment by wilddeer** [comment]
If you have a sticky at the very top of the page and `pageYOffset` becomes negative (in case of overscroll, I assume), it sticks to the top of the page (not viewport). This is how it's done in native implementation and you don't have any control outside of the page to do otherwise anyways.
