### ISSUE TITLE
top not set to zero problem

### ISSUE THREAD

**Issue by potsky** [wilddeer/stickyfill#19]
Hi !

I use this CSS :

```
.sticky {
	position : -webkit-sticky;
	position : sticky;
	top      : 70px;
}

.sticky:before,
.sticky:after {
    content: '';
    display: table;
}
```

When sticky is handle natively by the browser, no problem, it works, the sticky div is initialy at top 0px and when I scroll, it will stick at 70px from top.

When it is handled by javascript on Chrome and IE for example, the sticky div has the initial 70px on top instead of 0. And of course it sticks at 70px because it is already at 70px...

The 70px height is a fixed navbar on top. And the javascript behaviour is normal because given that Chrome or IE do not understand the CSS sticky position, they just set the content at 70px from the top of the parent instead of 0.

Any idea ?

**Comment by potsky** [comment]
If I add `margin-top: -70px` it works like a charm on Chrome and IE but my content is now 70px too high on Safari and Firefox... This is normal, they understand the sticky position and don't care about the top attribute when sticky div is displayed relatively to their parents.

I don't understand how I can set the initial position differently on all browsers.

**Comment by wilddeer** [comment]
Hey! I'll look into this in a couple of days, too busy at the moment.

**Comment by potsky** [comment]
Thank you for your reply.

I will try to look for this bug but can you confirm that it is not a normal behaviour and the normal behaviour should be on Chrome for example to not apply the `top:70px` when the div is positioned relative ? And the `top:70px` should only be applied when the div is positioned absolute according to the viewport ?

If this is the normal behaviour, I will send you a merge request, just let me know please :-)

**Comment by wilddeer** [comment]
It should behave just like native sticky does. Looks like there's some sort of edge case I didn't account for with sticky block positioned at the very top of the page.

**Comment by wilddeer** [comment]
Can't reproduce this. Could you show me the demo?

**Comment by potsky** [comment]
Potsky
www.potsky.com



Do you Pimp my Log ?

**Comment by potsky** [comment]
Oups sorry it seems the link has not been copied...

Here is the demo : http://psk.io/1QX25Y7

**Comment by wilddeer** [comment]
this is what I see

![](http://i.gyazo.com/1da5d31859473acef590fd7272c4dbb8.png)

**Comment by potsky** [comment]
Really sorry...

Here is the correct link : http://psk.io/1AwfprW

**Comment by wilddeer** [comment]
Bootstrap columns have `position: relative`, which is overridden by `position: sticky` in Safari and Firefox and left intact in Chrome, since it doesn't recognize `position: sticky`. Here's your 75px. Override it with `position: static` or just another wrapper `div` inside the column.

**Comment by potsky** [comment]
Congrat's, you're right !

`static` position works well, thank you. Wrapping in an other div inside the column does not work because we lose the `row` parent height.
