### ISSUE TITLE
Call API outside of console

### ISSUE THREAD

**Issue by alexandreaco** [wilddeer/stickyfill#21]
Are API calls supported within my javascript files, or only within the console? 

For example, I have a sticky sidebar with interactive elements. It has drawers that open and close, causing varied heights throughout the user experience. I added Stickyfill.rebuild() within one of my functions, and nothing happens. However, if I type the same thing into the console, it fixes the layout. 

Is there another way to call rebuild(), or do I need to do something else to initialize Stickyfill?

*note, no javascript errors display. It simply doesn't work.

**Comment by wilddeer** [comment]
You're doing something wrong. Let me see the code.
