### ISSUE TITLE
Class addition on trigger

### ISSUE THREAD

**Issue by ottobyte** [wilddeer/stickyfill#25]
Hi, I may not have explained this well in the title. I'm wondering whether there's a way to have the class  
` <div class="sticky">Nav</div>` to: `<div class="sticky active">Nav</div>` or similar. 

The reason would be so that some other css could be attached to the same action. Great plugin btw! :+1:

**Comment by TrySound** [comment]
@ottobyte It's polyfill for css `positon: sticky`. In this case no more api than nodes manipulation.

**Comment by ottobyte** [comment]
That's a fair point.

**Comment by wilddeer** [comment]
see https://github.com/wilddeer/stickyfill/issues/20

**Comment by ottobyte** [comment]
Thanks v much wilddeer!
