### ISSUE TITLE
Fails to start when style property is missing

### ISSUE THREAD

**Issue by theSprankle** [wilddeer/stickyfill#26]
If the sticky element does not have style="top:0" set inline then it fails to activate. 

Works:
```
<h2 js-sticky" style="top: 0">Element</h2>
```

Fails:
```
<h2 js-sticky" style="top:auto">Element</h2>
<h2 js-sticky" style="">Element</h2>
<h2 js-sticky">Element</h2>
```

Also, I am not using jQuery

**Comment by wilddeer** [comment]
It doesn't work in browsers with native implementation without top specified either. `top` has to be specified for sticky positioning to work according to the spec.

It doesn't have to be inlined, setting it in stylesheet will work too.
