### ISSUE TITLE
Tips for avoiding the "jump" 

### ISSUE THREAD

**Issue by BenRacicot** [wilddeer/stickyfill#27]
I've noticed that when setting the offset:

```javascript
.sticky {
	position: -webkit-sticky;
	position: sticky;
	top: 55px;
}
```
On my dev project anything larger than top:55px; makes the sticky jump a few pixels instead of seamlessly transitioning to stuck as I scroll down the page. 

Are there any known causes/tips to avoiding this jumping issue and making smooth transitions to stuck state?

Also I could not replicate the issue on [jsfiddle](http://jsfiddle.net/BenRacicot/nfjtxx6x/)

**Comment by wilddeer** [comment]
I can't help you without seeing your project (or replication of the bug).
