### ISSUE TITLE
Add more specific usage instructions to documentation

### ISSUE THREAD

**Issue by ajsharp** [wilddeer/stickyfill#31]
I spent a couple of hours trying to debug the library and figure out why this plugin wasn't working. It turned out that the element I was trying to make sticky was nested within another element, and that was screwing up the "mode" calculation, and the sticky element was never making it into mode "1" -- the `position: fixed` mode.

I think it would be helpful to add a proper "Usage" section to the documentation that explained the recommended way to use the plugin, e.g. make sure the element you're trying to fix isn't nested in another element.

**Comment by diegocanal** [comment]
@ajsharp I have the impression you have not read the the [What it does](https://github.com/wilddeer/stickyfill#what-it-does) section and the [Pro tips](https://github.com/wilddeer/stickyfill#pro-tips) section. Also, this is a polyfill so you should understand how the CSS property position works when is set to sticky (on the browsers that support it of course). You can take a look at [Sticky positioning](https://developer.mozilla.org/en-US/docs/Web/CSS/position#Sticky_positioning).

You said:
>...the recommended way to use the plugin, e.g. make sure the element you're trying to fix isn't nested in another element.

**The element you are trying to make sticky actually can be nested in another element**, the key is that **the parent element has to be taller than the sticky element and you must have some space between the bottom of the sticky element and the bottom of its parent**. To make it more visual, imagin that once the bottom of the parent "touches" the bottom of the sticky element it "pushes" it upwards so it is not sticky anymore, that's the reason why if the parent has equal height as the child (the one that is suposed to be sticky),i.e. the bottom of both elements are already "touchig" each other, it never gets sticky.

Regards,
Diego

**Comment by wilddeer** [comment]
@ajsharp Stickyfill is not a plugin, it's a polyfill for an experimental CSS feature (it already works in Safari and Firefox without any js code).There're plenty of articles and docs explaining sticky positioning (like [this MDN article](https://developer.mozilla.org/en-US/docs/Web/CSS/position#Sticky_positioning), for instance).
