### ISSUE TITLE
Breaks when parent has CSS transform property

### ISSUE THREAD

**Issue by jozan** [wilddeer/stickyfill#32]
If I animate parent with VelocityJS if leaves stuff like this behind `transform: translateY(0px);` which causes Stickyfill break.

`transform` value could be anything f.e. `scale(1)`.

Test case:
https://jsfiddle.net/p56bgp4j/

Browser: latest Chrome.

**Comment by wilddeer** [comment]
Fixed positioning doesn't work inside transformed elements as expected, see [this stackoverflow answer](http://stackoverflow.com/questions/15194313/webkit-css-transform3d-position-fixed-issue#answer-15256339). Stickyfill is properly switching the state to fixed, but it doesn't do anything, and I don't know of any working solutions to this problem.

**Comment by nextgenthemes** [comment]
@jozan your fiddle has messed up code.

```
.sticky {
}
  position: -webkit-sticky;
```

This way it will work nowhere. But fixing this it only works in FF as you say.

**Comment by jozan** [comment]
Ah, right. I wasn't aware of transform creates new local coordinate system. That explains this issue. Thanks!

/J
