### ISSUE TITLE
Add .stuck class or similar when in stuck position?

### ISSUE THREAD

**Issue by nextgenthemes** [wilddeer/stickyfill#33]
I found this http://stackoverflow.com/a/26185431/2847723 but it only works with native sticky on firefox but with this polyfill on chromium it is adding the .stuck class no matter if stucked or not on the very first scroll event.

Also I am wondering if this even makes sense to rely on throttled scroll events. Isn't sticky(fill) to prevent exacly that? Or is stickyfill using the same as `jQuery( window ).on( 'scroll', function() {` on scroll would do? Since chromium still not supports this I am wondering if using this would be overthinking it and going back to some easy small jquery would be better for me.

Would it not make sense to also add a `.stuck` class with this polyfill either way? Problem is when native is detected it would still need to run but instead of changing styles just adding a class.

**Comment by ClintH** [comment]
I wrote [this snippet](https://gist.github.com/ClintH/cd5616d98b91a9a4cd28) to do the job for me. Seems to work in Chrome and Safari (native sticky)

**Comment by chrisblakley** [comment]
+1

**Comment by mccormjt** [comment]
+1

**Comment by madhaze** [comment]
+1

**Comment by wilddeer** [comment]
See #20. TL;DR: This is a polyfill for a specific browser feature and there won't be any additional functionality. Use other tools alongside Stickyfill or modify Stickyfill for your needs (keep in mind that it wont start in browsers with native `position: sticky` support).
