### ISSUE TITLE
Does this work with bottom: 0

### ISSUE THREAD

**Issue by jasonyarrington** [wilddeer/stickyfill#34]
I have been trying to create a sticky element that is positioned relative to the bottom of the parent element.

Here is an example:  [http://jmy.d.ffinno.com/sticky-fill/](http://jmy.d.ffinno.com/sticky-fill/)

In this example, you will see that there is an element the is positioned sticky to the top of the div and another one positioned sticky to the bottom of the div.  

In safari, they both work.  In chrome, using stickyfill, only the top one works.

If this is unsupported functionality or something that could be added, point me in the right direction and I will see if I can add it.

**Comment by wilddeer** [comment]
It's not supported. It shouldn't take too much effort to add this to Stickyfill, but I'm currently too busy.

**Comment by jasonyarrington** [comment]
Can you point me in a direction and I will fork this and give it a try.

**Comment by wilddeer** [comment]
Haven't worked on this project for a long time, so I'm in the same boat as you, really. Also, the code is pretty badly organized and poorly documented, which doesn't help remembering things at all :–) You'd have to figure out everything yourself, in case you really want to implement this.

**Comment by jasonyarrington** [comment]
Thanks for the candor.  :-).  No problem, I will give it a try.  I will either come up with something brilliant or an incredible hack.  :-)

**Comment by all4pages** [comment]
Hi jasonyarrington I am interrested in your question too. Did you try to get a solution for it?
