### ISSUE TITLE
Can this parse elements css and trigger if they have position: sticky?

### ISSUE THREAD

**Issue by corysimmons** [wilddeer/stickyfill#35]
It'd be better than manually specifying each selector as sticky.

You'd be able to simply drop `<script src="stickyfill.js">` into html and `position: sticky` would be polyfilled instead of having to put `<script src="stickyfill.js">` into the page, then go into JS and do something like: 

```js
var stickyElements = document.getElementsByClassName('sticky');

for (var i = stickyElements.length - 1; i >= 0; i--) {
    Stickyfill.add(stickyElements[i]);
}
```

**Comment by wilddeer** [comment]
Nope:

- Browsers don’t save CSS values they don’t understand → checking `getComputedStyle` won’t work
- Another method – parsing CSS and determining who’s gonna get sticky positioning – is a huge task in itself, lots of additional unnecessary code, big performance overhead, lots of quirks
- Drop-in solution won’t work with dynamic web apps

**Comment by corysimmons** [comment]
I bet it ccccccooooouuuuullllddddd work, but like you said, it'd be a ton of work and impossible to find the right balance on perf overhead. Aight. Just figured I'd ask. :)
