### ISSUE TITLE
Support for top: 0, bottom: 0?

### ISSUE THREAD

**Issue by matthew-dean** [wilddeer/stickyfill#37]
Wondering when there might be support for a sidebar that always stays in view, even if the sidebar is longer than the page (so a sidebar with overflow: auto). Seems like a pretty typical use case.

**Comment by steven0547** [comment]
Totally agree. Having the same concern for the website I'm working on right now.

**Comment by wilddeer** [comment]
Sorry for the late reply, didn’t have much time to work on my personal projects lately.

Not planning to add support for `bottom` in the nearest future, but you actually don’t need it for this kind of sidebar (if I understood what you meant correctly). Check out the sidebar on [Chatra’s API page](https://chatra.io/help/api/#settings) (you might have to squeeze the page to see the overflow).
