### ISSUE TITLE
Support for AJAX Pages

### ISSUE THREAD

**Issue by jonnitto** [wilddeer/stickyfill#40]
At the moment it is hard to implement this function when you use ajax. Our CMS loads in the backend the new pages with ajax. Unfortunately I've no BeforePageUnload event. It would be great to have the `Stickyfill.kill()` function work, event when the elements were removed from the dom tree.

**Comment by wilddeer** [comment]
`Stickyfill.kill()` works for me after I remove some of the stickies from the DOM
