### ISSUE TITLE
Flickering when used inside display: none

### ISSUE THREAD

**Issue by andreialecu** [wilddeer/stickyfill#44]
I have a page that has various tabs on it, inside these tabs I have some elements that use stickyfill.

Changing to a new tab makes all other tabs `display: none` and the current tab `display: block`. When this happens, the sticky element initially overlaps, then pushes all other content down after a few miliseconds. 

The delay depends on how close the interval is to firing in the `startFastCheckTimer` function.

The only workaround I see here is to use `requestAnimationFrame` as a fast loop and detect whether the element is currently hidden (offsetHeight/width are 0). If it is, don't initialize the polyfill. Keep track however on when it is made visible, and instantly initialize it then.

Any thoughts on this approach?

**Comment by astrotumult** [comment]
I am having a very similar issue. Did your workaround have the desired effect? Can you elaborate a little?

**Comment by wilddeer** [comment]
Sorry for the (very) late reply, didn’t have much time to work on my personal projects lately.

You have to manually call `Stickyfill.rebuild()` (`Stickyfill.refreshAll()` in latest version) after the tab is switched.

There’s no good workaround, `requestAnimationFrame` is essentially `setTimeout()` with some improvements for better animations. It’s not fit for this purpose and would call the check function too often which could lead to unresponsiveness in complex layouts.
