### ISSUE TITLE
Sticky table headers?

### ISSUE THREAD

**Issue by imakewebsites** [wilddeer/stickyfill#45]
I can't make `<thead>` elements sticky (at least not on Chrome). In your example your `<th>` example `TH {top: -40px; margin-bottom: 150px;}` doesn't seem to work either :(

**Comment by wilddeer** [comment]
http://d.pr/i/1fEPV

**Comment by spongessuck** [comment]
Chrome 56 now has native `position:sticky` support, even for table cells/headers.

**Comment by f3anaro** [comment]
@wilddeer Firefox 59 has native `position: sticky` [support for table parts](https://bugzilla.mozilla.org/show_bug.cgi?id=975644). Can the [guard](https://github.com/wilddeer/stickyfill/blob/b652aee4ceb8fed756a66690c61b874ca2005e97/src/stickyfill.js#L117) be removed in a new release of stickyfill?
