### ISSUE TITLE
Does this thrash layout?

### ISSUE THREAD

**Issue by davidosomething** [wilddeer/stickyfill#47]
getBoundingClientRect calls and others used by this repo are known to thrash layout:
http://ricostacruz.com/cheatsheets/layout-thrashing.html

Would it help offload computation to `requestIdleCallback` / `requestAnimationFrame`?

**Comment by wilddeer** [comment]
It doesn’t cause any repaints while idle, I don’t see the reason to bother:

![](http://d.pr/i/1iAyO+)

It will of course cause repaints while initializing and changing sticky states, but they are kept to the minimum.
