### ISSUE TITLE
Callback support

### ISSUE THREAD

**Issue by blackwood** [wilddeer/stickyfill#49]
I'm wondering if you might ever bake support for a callback into this plugin.

Consider this use case: someone may want to conditionally style, change the behavior, or add a class to an element depending on whether or not `position: sticky` is available in the current browser.

Here's a possible way one could achieve this. First abstract the support test so that it returns a `true` or `false` value instead of committing `seppuku` immediately:

``` js
var isSupported = function() {
    //test for native support
    var prefixes = ['', '-webkit-', '-moz-', '-ms-'],
        block = document.createElement('div');

    for (var i = prefixes.length - 1; i >= 0; i--) {
        try {
            block.style.position = prefixes[i] + 'sticky';
        }
        catch(e) {}
        if (block.style.position != '') {
            return true;
        }
    }
    return false;
}
```

Then inside of the `init` method, the class could allow access to the return value of that test function, before committing `seppuku()`. This could be passed along by the `add` method.

``` js
function init(callback) {
    if (initialized) return;

    var support = isSupported();

    callback.apply(this, [support]);

    if (support) seppuku();

    //...etc.
}
// ... and:
function add(node, callback) {
    //check if Stickyfill is already applied to the node
    for (var i = watchArray.length - 1; i >= 0; i--) {
        if (watchArray[i].node === node) return;
    };

    var el = getElementParams(node);

    watchArray.push(el);

    if (!initialized) {
        init(callback);
    }
    else {
        initElement(el);
    }
}
// ... later:
$.fn.Stickyfill = function(callback) {
    this.each(function() {
        Stickyfill.add(this, callback);
    });

    return this;
};
```

In fact, by passing along the `node` argument into `init` as well, you could give the user immediate access to the node itself, which would make it even easier to supply a function that may need to operate on that particular node.

What do you think?

**Comment by wilddeer** [comment]
Sorry for the late reply, I didn’t have much time to work on my personal projects lately.

This is way out of the scope of this polyfill. There are lots of specialized feature detection tools out there, and the test function itself is tiny and very common, it can be easily used outside of this polyfill. I don’t see why this should be a callback for Stickyfill initialization. You can “conditionally style, change the behavior, or add a class” at any moment before or after Stickyfill initialization.

I won’t bloat Stickyfill with bells and whistles, sorry.

**Comment by blackwood** [comment]
¯\_(ツ)_/¯ this was over a year ago, may as well have just closed the issue without the sanctimony
