### ISSUE TITLE
IE11 wrong positioning

### ISSUE THREAD

**Issue by parker789** [wilddeer/stickyfill#51]
Hello,

I've been hunting for the solution to this most of the day now, and am now resorting to ask a question!  I'm using stickyfill in my app, and it works fine in Crome / Firefox (kills itself perfectly) but not IE11.. sort of.  The left positioning on each state is wrong, and removing the `left: <Z>px` immediately solves my issue, but I can't seem to figure out why stickyfill.js is setting the wrong values in the first place.

Any insight into the problem would be very helpful! Thanks

**Comment by wilddeer** [comment]
can’t say anything without a reproduction of the issue

**Comment by parker789** [comment]
Yeah, just didn't know if I'd get lucky.  Its super hard for me to recreate because I'm on OS X.  If i can get a working snippet to link here I will.

**Comment by yowainwright** [comment]
Seems like this should be closed since @parker789 didn't present a snippet.
