### ISSUE TITLE
Doesn't allow me to use scrollpad on laptop to scroll on Chrome

### ISSUE THREAD

**Issue by Modicrumb** [wilddeer/stickyfill#52]
OSX version: 10.11.6
Macbook air

Google Chrome Version: 53

When I use the plug in I simply can't scroll using the scrollwheel on the laptop... I can only scroll using the mouse.

**Comment by wilddeer** [comment]
Sorry for the late reply, I didn’t have much time to work on my personal projects lately.

I can’t reproduce this issue, if this is still relevant, please provide a live reproduction (e.g. link to the site where this happens).
