### ISSUE TITLE
Rebuild after deletion/hidden element

### ISSUE THREAD

**Issue by amoeban** [wilddeer/stickyfill#53]
I have a page with multiple sticky elements. Some of them are shoutouts that the user can hide.

What i do is 

`$('#fixed-top').on('changeLayout', stickyChange);`

then the stickyChange function

`function stickyChange() {
var fixedHeight = $('#fixed-top').height() + $('#fixed-top-2').height();
$('.sticky').scrollableIfTooLarge(40).css({ top: fixedHeight });
Stickyfill.rebuild();
}`

What I do is that I calculate the new fixed top height (shoutouts and a header are fixed), so I get the offset for the other elements.
The update of top on each element works fine but when I call rebuild, the old height is used. How should I update the elements so they use the new top value in rebuild?

**Comment by wilddeer** [comment]
Sorry for the late reply, I didn’t have much time to work on my personal projects lately.

If this issue is still relevant, please provide a live reproduction (link to the site/codepen/jsfiddle).
