### ISSUE TITLE
non-float

### ISSUE THREAD

**Issue by beachmat** [wilddeer/stickyfill#57]
It seems that position:sticky only works when using floats for layouts rather than display:table or flexbox - is that correct?

**Comment by andrey-hohlov** [comment]
+

**Comment by wilddeer** [comment]
Sorry for the late reply, I didn’t have much time to work on my personal projects lately.

Stickyfill doesn’t work with table elements, but it should work fine with table descendant elements, as well as flex elements.

If you have a case where Stickyfill doesn’t behave nicely with either of these, please provide a live reproduction (link to the site/codepen/jsfiddle).
