### ISSUE TITLE
Doesn't work on Firefox 50.1.0

### ISSUE THREAD

**Issue by OzgurGorgulu** [wilddeer/stickyfill#62]
Stickyfill doesn't work on Firefox 50.1.0. :(
Works on Chrome 55.0.2883.87m, Opera 42.0.2393.137, Edge 38.14393.0.0.

**Comment by wilddeer** [comment]
Stickyfill doesn't do anything in Firefox because Firefox supports `position: sticky` natively. If some sticky block doesn't work in a browser that supports it natively it's a sign you did something wrong (or a bug in a browser which I doubt).

**Comment by jguffey** [comment]
Firefox doesn't support sticky table cells, see: [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=975644).

The Readme says "~works with table cells~ disabled until Firefox makes a native implementation", which sort of confuses me. If Firefox doesn't support sticky table cells yet, isn't that why we'd use a polyfill?

**Comment by wilddeer** [comment]
@jguffey there’s no way to detect if sticky table cells are supported in a particular browser (as far as I know). So for now the polyfill sticks with the lowest denominator, which is FF implementation.
