### ISSUE TITLE
False positive on when `position: sticky;` isn't supported

### ISSUE THREAD

**Issue by chrishutchinson** [wilddeer/stickyfill#65]
Hey,

I've been trying to use `stickyfill` and it calls the `seppuku()` method even though `position: sticky;` isn't supported.

I've done a fork which uses `CSS.supports()` to verify if `position: sticky;` is supported, and wrapped it in a `try / catch` in case `CSS.supports()` is not supported (which confirms `position: sticky;` isn't supported).

If I PR'd this change would that be acceptable?

https://github.com/times/stickyfill/blob/master/src/stickyfill.js#L31

**Comment by wilddeer** [comment]
> it calls the seppuku() method even though position: sticky; isn't supported.

What browser did you use?

> If I PR'd this change would that be acceptable?

I'm currently working on a 2.0 version so I won't accept PRs to the current version. But if the false positive is confirmed I will fix it in 2.0.
