### ISSUE TITLE
Contradiction regarding horizontal support in README

### ISSUE THREAD

**Issue by satiewaltz** [wilddeer/stickyfill#66]
README states that this polyfill works will with horizontal page scrolling:
```
mimics original position: sticky behavior:
... behaves nicely with horizontal page scrolling,
```

But later says it doesn't support left or right stickies which are used for horizontal page scrolling:
```
doesn't support left, right, bottom or combined stickies,
```

**Comment by wilddeer** [comment]
Sorry for the late reply, I didn’t have much time to work on my personal projects lately.

“behaves nicely with horizontal page scrolling” means the regular top stickies behave as expected when the page is scrolled horizontally. Maybe it needs a rephrasing, I’ll look into it.
