### ISSUE TITLE
Is there IE11 Support for this

### ISSUE THREAD

**Issue by MarineIK** [wilddeer/stickyfill#67]
As usual Microsoft is behind the curb. I don't know why they even bother anymore.

**Comment by Grawl** [comment]
It works, you just have to use [`transform-object-assign`](https://babeljs.io/docs/plugins/transform-object-assign/) plugin for Babel.

**Comment by vaijan1990** [comment]
I am using javascript and jquery. Currently not using babel. Is there a way to achieve this in IE11?

**Comment by Grawl** [comment]
Oh sorry I just make a mistake when I bundle my JS last time (I was trying to figure out why it's not working in IE 11). You have not use Babel, last version works out-of-the-box. I used [Decor-Aid/stickyfill](https://github.com/Decor-Aid/stickyfill), FYI: in repo it has old, buggy version, but from NPM I have fixed version with `var key in sourceObject` fix

**Comment by wilddeer** [comment]
Sorry for the late reply, I didn’t have much time to work on my personal projects lately.

Stickyfill supports IE9+. If you have problems with it working in IE, please provide a live reproduction of the issue.
