### ISSUE TITLE
Using Stickyfill with webpack

### ISSUE THREAD

**Issue by KKSzymanowski** [wilddeer/stickyfill#69]
Currently if I `import` or `require` stickyfill
```js
import Stickyfill from 'stickyfill';
// or
const Stickyfill = require('stickyfill');
```
the returned value doesn't contain methods mentioned in the API section for the Readme.
It however returns a function:
![image](https://cloud.githubusercontent.com/assets/13980973/25066285/2013626a-2222-11e7-9d88-4c211fa98448.png)
which when called indeed returns the desired object.
Is this an expected behaviour? Should I use
```js
Stickyfill().add()
```
instead of 
```js
Stickyfill.add()
```
or am I missing something?

**Comment by darylteo** [comment]
@KKSzymanowski what you're missing is that the npm version is not maintained by @wilddeer , but by @coreh.

**Comment by KKSzymanowski** [comment]
@darylteo I'm not sure what you mean. Does @coreh maintain a fork of this package?

**Comment by darylteo** [comment]
@KKSzymanowski  not so much a fork, but a copy paste of source and hasn't been updated.

https://github.com/webmodules/stickyfill

**Comment by KKSzymanowski** [comment]
From what I see, the module required from this fork also is a function which evaluates to the Stickyfill object:
![image](https://user-images.githubusercontent.com/13980973/27578278-f1129eaa-5b23-11e7-9c44-ae9a43b674af.png)

It's probably the way to use it.
