### ISSUE TITLE
Does this support IE11?

### ISSUE THREAD

**Issue by vaijan1990** [wilddeer/stickyfill#73]
I am trying to use this plugin for my project. But I am unable to get it work in IE11. I am using vanilla js and jquery in my project.

**Comment by ccalvarez** [comment]
Hi @vaijan1990,
I've just implemented it in a Vue.js project, and it's working fine in Internet Explorer 11.540.15063.0.

I've followed instructions given in this [link](https://github.com/wilddeer/stickyfill).

I'm using ES6 "import" syntax, but it works with "require" syntax as well:

`import Stickyfill from 'stickyfill';`   <== change this to: `var Stickyfill = require('stickyfill');`

and then:

```
//Vue.js component:
updated() {
    const stickyfill = Stickyfill();
    let stickyElements = document.getElementsByClassName('sticky');
    for (let i = stickyElements.length - 1; i >= 0; i--) {
      stickyfill.add(stickyElements[i]);
    }
  },
```
 
which in your case can be:

```
var stickyElements = document.getElementsByClassName('sticky');

for (var i = stickyElements.length - 1; i >= 0; i--) {
    Stickyfill.add(stickyElements[i]);
}
```

Don't forget to set your CSS style for the 'sticky' class.

This link also helped me:  https://www.npmjs.com/package/stickyfill

**Comment by ccalvarez** [comment]
I don't use it directly but via this npm package:  https://www.npmjs.com/package/stickyfill and it is working fine with Internet Explorer 11.540.15063.0.

**Comment by xjure** [comment]
I used it on this site, and it doesn't work in IE 11
https://www.zsem.hr/kontakti/

Can you check it and tell me what I'm doing wrong, thanks.

**Comment by nagyt234** [comment]
Dear @xjure, It seems to work on your page. What did you do? I have the same problem on my site: [https://www.diet-health.info](https://www.diet-health.info)

**Comment by wilddeer** [comment]
Sorry for the late replies, I didn’t have much time to work on my personal projects lately.

@nagyt234 you have to initialize Stickyfill on the sticky elements, e.g. `$('.sticky').Stickyfill();` works just fine on your page.

@xjure seems to be the same issue, you have’t initialized Stickyfill on any elements.

@vaijan1990 I have to see your project if this issue is still relevant for you. Can’t say anything without live reproduction of the issue.

**Comment by Jain-tech** [comment]
I am using this in my vuejs project but it doesn't seems to run on IE11
