### ISSUE TITLE
Error while importing on server side

### ISSUE THREAD

**Issue by alesdrobysh** [wilddeer/stickyfill#74]
While running a unit-test in node environment for my component that uses Stickyfill as a dependency I am getting the following `ReferenceError: Stickyfill is not defined` thrown out from `node_modules/stickyfill2/dist/stickyfill.js:467:18`

I see the following solution for this - export `window.Stickyfill` rather than just `Stickyfill`, it works well in combination with JSDOM.

**Comment by wilddeer** [comment]
Sorry for the late reply, I didn’t have much time to work on my personal projects lately.

It seems that you used third party UMD wrapped version. I can’t possible know what went wrong there. Try using the latest version, it’s now officially on npm under `stickyfilljs`. Bare in mind that the API has changed.

**Comment by alesdrobysh** [comment]
thanks!

**Comment by liuhelen10** [comment]
@wilddeer I'm encountering an error trying to use this in my isomorphic app. Getting this server error on my `import` line (`import Stickyfill from 'stickyfilljs';`):

`ReferenceError: window is not defined`

I"m using version 2.0.3
