### ISSUE TITLE
Stickyfill's module dist redefine's the window object, always commits 'seppuku'

### ISSUE THREAD

**Issue by soluml** [wilddeer/stickyfill#76]
I'm having a lot of trouble getting this polyfill to work.  I can see that it's installed, and I can add elements to stickyfill, but it doesn't seem to do anything. I've tried your test page and verified it working in IE11, so I'm wondering if there's some sort of collision with another library going on.

Below is a screenshot of my console in Browserstack.  You can see both elements are there and both are `_stickyMode = null`.  One is a H1 element whose only parent is the `<body>`. The other is a nav element that is `position: sticky` and works in Chrome without Stickyfill.

![image](https://user-images.githubusercontent.com/589571/31250480-7f3a9452-a9e0-11e7-834d-6dea7729697c.png)

I'm pulling in the library asynchronously like so: 

```
if (!Modernizr.csspositionsticky) {
    promises.push(
      // tslint:disable-next-line
      import(/* webpackChunkName: "sticky-polyfill" */ 'stickyfilljs')
        .then((stickyfill) => {
          window['Stickyfill'] = stickyfill;
        }),
    );
  }
```

And using it like so:

```
// Apply Position Sticky polyfill
if (!Modernizr.csspositionsticky) {
  window['Stickyfill'].add(document.querySelectorAll('.section__tabs'));
}
```

Any ideas for troubleshooting?

**Comment by wilddeer** [comment]
Hi, I need to see your page to help you.

**Comment by wilddeer** [comment]
whoops, didn’t mean to close

**Comment by soluml** [comment]
I've figured out the issue... sorta.  It's committing Seppuku in my IE11, so there's definitely a collision.

I'll try to get a test page up here shortly, but I suspect it might be Modernizr.

**Comment by soluml** [comment]
window.getComputedStyle is returning undefined when the Module is run.  In my IE11's console, it's working as expected.

**Comment by soluml** [comment]
The problem is [this line here](https://github.com/wilddeer/stickyfill/blob/master/dist/stickyfill.js#L506).  When used as a module, `this` is not the window object, so you end up redefining window for the rest of the script.

**Comment by soluml** [comment]
As others have mentioned in #54 and #43, I'd leave feature detection off. It'd be better to assume the browser's broken and leave feature detection up to a library like [Modernizr](https://modernizr.com/download?csspositionsticky-setclasses&q=sticky).

**Comment by wilddeer** [comment]
Oh, I see. I’ve tested a bunch of bundlers and they didn’t mess with `this`, so it slipped past me. 

I use these args for better minification, actually. They become `a` and `b` in [minified version](https://github.com/wilddeer/stickyfill/blob/master/dist/stickyfill.min.js). It’s not much, but I’ll accept your PR and leave them be.

As for the feature detection, I won’t remove it completely, but I’m planning to add an option to disable it.

Thanks!

**Comment by soluml** [comment]
Sounds good, thanks!
