### ISSUE TITLE
Can we add support for overflow:scroll blocks?

### ISSUE THREAD

**Issue by sam-dupras** [wilddeer/stickyfill#79]
We would need to change the API a little bit so that we can bind the stickyfill to a particular block instead of the whole page, not to mention we may have multiple scrollable blocks on a single page.

Any reason why this hasn't been done already? I can start working on a fix for this if its desirable?

**Comment by wilddeer** [comment]
The reason is me being lazy, mainly. This shouldn’t change the API, actually. But instead of one global scroll listener we would need one for each overflow context. I’ll poke around it in the next few days.

**Comment by sam-dupras** [comment]
Thanks, I think this would be incredibly useful, let me know if you would like some help figuring this out.

**Comment by wilddeer** [comment]
Hey, so I tried different approaches and the major problem is that there’s no good way to make fixed positioning work inside a scrollable block.

One way is to make a wrapper div and position sticky block inside it. The cons of this approach:
- wrapper modifies the DOM structure, can potentially mess up the styles and other things
- sticky block has to be moved up in the DOM tree to be absolutely positioned in the wrapper (again, DOM modifications)
- has to somehow account for scrollbar widths
- hard to implement stickies that are partly covered by the edge (e.g. `top: -10px`)

So this isn’t really an option.

The other way is to set a zero transform (`transform: translateX(0)`) to scrollable block which forces new coordinate system on that block. This works in IE and Edge, fixed block becomes fixed inside the scrollable area, but the block flicks and jerks, doesn’t look very nice. In Chrome and FF fixed block becomes absolutely positioned.

So it’s not really worth it. It won’t work in old Chrome and FF versions and it looks crappy in IE/Edge.

If you have any ideas of how to implement this, please share.

Closing for now.

**Comment by DanielRuf** [comment]
It seems this is unfixable on IE11 and other browsers which do not support sticky elements. =/

**Comment by sylwiamikolajczuk** [comment]
Is there any workaround for this? Something one can for a specific project, without having to worry much about DOM modifications, compatibility with every older browser (except for IE11 :( ) etc?
