### ISSUE TITLE
Make an option to force enable the polyfill

### ISSUE THREAD

**Issue by wilddeer** [wilddeer/stickyfill#81]

**Comment by atomcorp** [comment]
For people who comes across this:
I found Edge support for position: sticky was so unreliable, forcing this polyfill on it was a better option. For anyone who's curious, I hacked the following: 

    // The polyfill cant’t function properly without `getComputedStyle`.
    if (!window.getComputedStyle) seppuku = true;
    // Dont’t get in a way if the browser supports `position: sticky` natively.
    else {
        const testNode = document.createElement('div');

        if (
            ['', '-webkit-', '-moz-', '-ms-'].some(prefix => {
                try {
                    testNode.style.position = prefix + 'sticky';
                }
                catch(e) {}

                return testNode.style.position != '';
            })
        ) seppuku = true;
    }
    + // hack to force ignore MS Edge sticky support
    + if (/Edge/.test(navigator.userAgent)) {
    +    seppuku = false;
    + }

wilddeer:
I'd have liked to have provided a something a bit more solid improvement, but not sure how it would work with the existing initial test, and if a rewrite would be OK. I'd be happy to have a go if you could offer some idea of what you were planning.

**Comment by eleweek** [comment]
Yep, this feature would be so nice to have! 

Editing a postion:sticky-ied input in chrome 61 forces a scroll to the top. I'd love to use this polyfill instead of native support.

**Comment by liuhelen10** [comment]
@wilddeer any movement on this? perhaps we could just provide an initialization option to force the polyfill? i.e. 

```
const stickyFill = new Stickyfill({ forceSticky: true });
```

**Comment by wilddeer** [comment]
We now have `Stickyfill.forceSticky()`. Rejoice!
