### ISSUE TITLE
[IE11][Win8.1] Error: Unable to get property 'position' of undefined or null reference

### ISSUE THREAD

**Issue by glukki** [wilddeer/stickyfill#85]
Error source: https://github.com/wilddeer/stickyfill/blob/2.0.3/src/stickyfill.js#L23

**Comment by vivekhomebell** [comment]
Me too got the same issue.

**Comment by glukki** [comment]
IDK what fixed it, but maybe I just made polyfill start after DOM was loaded

**Comment by seleckis** [comment]
I would reopen this issue, because I have the same problem. Stickyfill work only if we pass only one element in add method.

This works:
```
Stickyfill.add($(".sticky").get(0));
```
These ones doesn't:
```
Stickyfill.add($(".sticky"));
```
```
Stickyfill.add($(".sticky").toArray());
```
