### ISSUE TITLE
Too late setting from position fixed to absolute in IE 11

### ISSUE THREAD

**Issue by quenit** [wilddeer/stickyfill#88]
Take a look of this URL https://www.bohlmeier.de/ and the section with a headline "Die Verpackung mit Überraschungseffekt ".

This part works sticky in the rest of the browsers fine, but in IE11 with stickyfill for some reason the sticky section get position absolute first when the next text part goes pretty to the top of the sticky container. 

You can best see it with maximized browser  by a full HD monitor, because there ist video play fallback in the case of small screen.

**Comment by wilddeer** [comment]
It happens because you dynamically change the height of this block:
![screenshot](https://i.gyazo.com/60f76ff4129fadd27f25c7bb31152d9a.png)

Calling `Stickyfill.refreshAll()` whenever the block changes its height should fix this.
