### ISSUE TITLE
plugin for WP not working

### ISSUE THREAD

**Issue by MartinDivartu** [wilddeer/stickyfill#89]
Hi.

I tried many sticky plugins on wordpress site but only your code works. It's great !! I created a plugin to make some effect shortcode.
I really don't know why your plugin works on one wp page but not on another .
jQuery seems to be the same.

one page where it works http://www.egosurfer.sk/
second where it's not working http://www.makra.sk/index.php/wp/

would you please help ?

Thanks

**Comment by wilddeer** [comment]
It doesn’t work because of `overflow-x: hidden;` on `.site-container`, see https://github.com/wilddeer/stickyfill#pro-tips 3rd paragraph.
