### ISSUE TITLE
Interaction with position: fixed breaks on IE 11

### ISSUE THREAD

**Issue by mattthr** [wilddeer/stickyfill#90]
Hi,

Sorry I've not traced this harder, but I noticed the script wasn't working with my site in IE11. On investigation, I've traced this to having the sticky element nested inside a position: fixed element.

Reproduction here .. the "assign" block on the right should be sticky:
https://jsfiddle.net/y3e058tf/2/

Seems to work okay in more recent browsers, including Chrome and Edge. It's possible that there's something else causing the issue other than just position: fixed ... I've just noticed that removing it fixes the issue. Sadly, it also breaks the entire layout :(

Advice/fix would be appreciated.

Cheers,
Matt

**Comment by wilddeer** [comment]
This polyfill doesn’t support stickies in overflowed blocks.
