### ISSUE TITLE
Types folder is not available.

### ISSUE THREAD

**Issue by pacoita** [wilddeer/stickyfill#93]
Hi, 

Could it be that the latest change introducing the types folder has not been properly published?

Doing `npm install stickyfilljs --save` still downloads the old version without typings.

Thanks

**Comment by h-shiratsuki** [comment]
It has not been released yet.
Try `npm install wilddeer/stickyfill`.

**Comment by pacoita** [comment]
@h-shiratsuki Thanks for the reply. 
Will though future updates to the library flow automatically also into wilddeer/stickyfill?

**Comment by h-shiratsuki** [comment]
@pacoita Maybe, it is DNS name resolution error.

https://stackoverflow.com/questions/9393409/ssh-could-not-resolve-hostname-github-com-name-or-service-not-known-fatal-th
