### ISSUE TITLE
which lacks return-type annotation, implicitly has an 'any' return type.

### ISSUE THREAD

**Issue by h-shiratsuki** [wilddeer/stickyfill#95]
'removeOne', 'remove', 'removeAll', which lacks return-type annotation, implicitly has an 'any' return type.

Please set 'void' to return type.

**Comment by wilddeer** [comment]
Hey, I don't use typings myself, please make a pull request.

**Comment by h-shiratsuki** [comment]
@wilddeer OK. I created a pull request.
